arch: amd64

os: linux

dist: xenial

language: java

jdk: oraclejdk11

before_install:
 - rvm get stable 
 - rvm install ruby-3.0.0
 - rvm use ruby-3.0.0
 - gem install hiptest-publisher
#generate test classes from cucumberstudio testrun id
#- hiptest-publisher --config-file java-junit.conf --test-run-id 524844 --without=actionwords

script:
 - java --version
 - mvn package
 - cd target/surefire-reports/
 - ls
 - cd -

after_script:
 - hiptest-publisher --config-file java-junit.conf --push "target/surefire-reports/TEST-com.xyz.loginsystem.*.xml" --test-run-id 524844 --push-format junit
