arch: amd64

os: linux

dist: xenial

language: java

jdk: oraclejdk11

before_install:
 - rvm get stable 
 - rvm install ruby-3.0.0
 - rvm use ruby-3.0.0
 - gem install hiptest-publisher
 - hiptest-publisher -c hiptest-publisher.conf --only=tests --test-run-id=524844

script:
 - java --version
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e
 - mvn '-Dtest=com.xyz.LoginSystem.*Test' test

after_script:
 - hiptest-publisher -c hiptest-publisher.conf --push="nosetests.xml" --test-run-id=524844

env:
  global:
    - secure: "ZnHbR/sUlF4Gk8GQ54mFVwqjdlmoCsGTycQQ+ZX97X4k2Pm6SiW0AjC37kxLlJHY1tNtpujQanQEixi302KGchqYp2trHgSGn72KmCr+MG1m+MX7s8gjORKVW4BtoiU9U3TdSTMonCXxm9CT92+fExVO9MjDb//Tb58EAjuA/MlcFb0f7BFLUpk/sOb/LI4SVVd8S05iC3kWK/HY20BnOj5gJeU+TdggZjjHtrbYgiOhFN30Z5yFXzONZscKB/Xn25QNnPvlGHlVc7Ssuxzjiu4NyWEJq48YfzL39S8ZYrZPs1f0Qds+Gy+5hUO4OE9lQka10l998NFc9u6dxBCXi7Ox0G5c+4wKnXQtdXUsbkZDreT7UfRCNgygwT/NlSzEXrBVSxCOBatFDtC07lEMVyNSaJ1z8DwUYhMtriZ1BTXnpFKAvhlK0keXhqabPJKk3Yhb0IoOAggWvFMwUX0Al0LntsFE59ne9TCAP0bsGB3eood6Im/IjUpvspAr49gzSf4eGM/5mzYaaYAI/iQBwbxPNZfri9NFHn29Q6ZILaDcomUDCyJFyStV9K4rW2200t1mudnUlFjLtVvGWEiDdmhQNxND6jEpiekMIMZfOs0BSh5XJZI0BFfFFEbGDMlNu0nN7Tm19sAdrtKqb3TeJSIs5vclRlC+nG4qnGyBrT8="
